stages:
  train:
    cmd: python train.py
    deps:
      - train.py
      - PlantVillage
    params:
      - data
      - model
      - training
      - paths
    outs:
      - plant_disease_model.h5
      - plots/:
          cache: false
    metrics:
      - metrics.json:
          cache: false

